// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Database;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    [Migration("20230305103526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Database.Dtos.ProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectDtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 12,
                            Description = "DGMCXXHVDRRFHXSLXEXZ",
                            EndDate = "10/04/2024",
                            Members = "IRLGY",
                            Name = "DTUJB",
                            ProjectState = "InProgress",
                            Rating = 2.0,
                            StartDate = "5/03/2023",
                            Steck = "IHESDJJYQWHXTDEKTERK"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 16,
                            Description = "WLERDCQFTHMLAAZDCRZP",
                            EndDate = "10/04/2024",
                            Members = "OUAYB",
                            Name = "PWLBM",
                            ProjectState = "InProgress",
                            Rating = 4.0,
                            StartDate = "5/03/2023",
                            Steck = "KZPCMOPOAZCAAZNKVKKT"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 17,
                            Description = "CNTFYLFCEMISTSQTMXJE",
                            EndDate = "10/04/2024",
                            Members = "LYJGA",
                            Name = "QAYBW",
                            ProjectState = "Planning",
                            Rating = 2.0,
                            StartDate = "5/03/2023",
                            Steck = "DODOQLZYGTXXUUKPIOKG"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 14,
                            Description = "UCRMHLTJQCAEZIDSRXTK",
                            EndDate = "10/04/2024",
                            Members = "BIIQW",
                            Name = "INLJS",
                            ProjectState = "Planning",
                            Rating = 3.0,
                            StartDate = "5/03/2023",
                            Steck = "JQTVNVVPHHOMMLHAKLYU"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 23,
                            Description = "DHRGZOVGXNCCKCFAJGRG",
                            EndDate = "10/04/2024",
                            Members = "EDELN",
                            Name = "VDSTK",
                            ProjectState = "Completed",
                            Rating = 4.0,
                            StartDate = "5/03/2023",
                            Steck = "GNLGIYBVUKGCCLZPAHBT"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 21,
                            Description = "CZAAMECQXOSEKOPOVVMX",
                            EndDate = "10/04/2024",
                            Members = "QKHDM",
                            Name = "UWFSA",
                            ProjectState = "Completed",
                            Rating = 1.0,
                            StartDate = "5/03/2023",
                            Steck = "RUIJPDKEVMYJGVLXHHWR"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 20,
                            Description = "SATBCLDUIFSXPZCMAHOE",
                            EndDate = "10/04/2024",
                            Members = "ACDAQ",
                            Name = "AQBWB",
                            ProjectState = "Planning",
                            Rating = 2.0,
                            StartDate = "5/03/2023",
                            Steck = "GYVHPGANBKZVBCUFPUYN"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 25,
                            Description = "UEBAURMADGJLSTKGWIRE",
                            EndDate = "10/04/2024",
                            Members = "EADEU",
                            Name = "NYUHU",
                            ProjectState = "InProgress",
                            Rating = 2.0,
                            StartDate = "5/03/2023",
                            Steck = "OAVXDJOGWMQSFMQBAJWI"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 23,
                            Description = "ZFYNUJBDNNHMWUJDQTAU",
                            EndDate = "10/04/2024",
                            Members = "VVCMD",
                            Name = "YFWNJ",
                            ProjectState = "LookingForParticipants",
                            Rating = 4.0,
                            StartDate = "5/03/2023",
                            Steck = "PXEIXQNMOYWBYHERLCGW"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 15,
                            Description = "HOLMZAZURPAWZYDJJJXC",
                            EndDate = "10/04/2024",
                            Members = "KVDGY",
                            Name = "YIQBT",
                            ProjectState = "InProgress",
                            Rating = 2.0,
                            StartDate = "5/03/2023",
                            Steck = "RNIVHUADAZJHJWRJNMRI"
                        });
                });

            modelBuilder.Entity("WebAPI.Database.Dtos.ResumeDto", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("created_at")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pd_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resume_template")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resume_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updated_at")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ResumeDtos");
                });

            modelBuilder.Entity("WebAPI.Database.Dtos.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "CDPOJYAJYELPBBWCWUCC",
                            Email = "FEYRIFH",
                            Name = "GKVSQ",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "ZAZUNVOOYAQIFHNDVNEA",
                            Status = "Planning",
                            Title = "SNIOTFMPCW"
                        },
                        new
                        {
                            Id = 2,
                            Description = "BRGVBVSGLBJFEVRGTSOB",
                            Email = "OAPKEJH",
                            Name = "AJCIV",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "ZXSWGCAAQVAXYCIUVKIG",
                            Status = "LookingForParticipants",
                            Title = "OPMGORACOP"
                        },
                        new
                        {
                            Id = 3,
                            Description = "UKDUYGBRKUJBDMVHRTPJ",
                            Email = "CAPQZLG",
                            Name = "OQJRX",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "LKYVGYWXLCPKBTUPJVBF",
                            Status = "LookingForParticipants",
                            Title = "IUACFFCNXX"
                        },
                        new
                        {
                            Id = 4,
                            Description = "WTDNTXVMEYKCUNRQZMRQ",
                            Email = "VNQBZZO",
                            Name = "DNXSS",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "QECJYQWJVJNBRQVWDLNG",
                            Status = "InProgress",
                            Title = "ILKDWRCYOX"
                        },
                        new
                        {
                            Id = 5,
                            Description = "XYOTICHRLXZRIZNXQPBQ",
                            Email = "CRHOAAZ",
                            Name = "XEPBY",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "EWYSJIIJWTVJXZVBDYUK",
                            Status = "Completed",
                            Title = "ZTSHDGDXAX"
                        },
                        new
                        {
                            Id = 6,
                            Description = "SIIPNVWNVSHASYSLDDZY",
                            Email = "PTAMVTY",
                            Name = "HNZQQ",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "HXEZSULUORKJDORMLWRN",
                            Status = "InProgress",
                            Title = "LEHIDONIJK"
                        },
                        new
                        {
                            Id = 7,
                            Description = "EHYNGWBNKIOOTMPXLVXY",
                            Email = "SOSGUDK",
                            Name = "TAOSL",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "TJZUUVVQORWJCZTRSMBB",
                            Status = "Completed",
                            Title = "NGQKQNXHHN"
                        },
                        new
                        {
                            Id = 8,
                            Description = "PWVSNEKASRTWECTSBTIA",
                            Email = "FDQGDAZ",
                            Name = "THBOR",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "LQXJAJEZHSVOIMRXMBHC",
                            Status = "Completed",
                            Title = "IDTLMEWOBW"
                        },
                        new
                        {
                            Id = 9,
                            Description = "ACXWTQGXBSCHTBXQLDUI",
                            Email = "CCNJEPM",
                            Name = "YGNRJ",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "KQHALYZXWAUCNRJUNGGS",
                            Status = "InProgress",
                            Title = "XJJWISFJVI"
                        },
                        new
                        {
                            Id = 10,
                            Description = "OVDDCDLDGQMOHXGETSLS",
                            Email = "YTIHFHI",
                            Name = "RGOED",
                            ProjectId = 0,
                            ResumeId = 0,
                            Skills = "GKIAPMYPEENBXFKXXBGS",
                            Status = "Planning",
                            Title = "IRWOFPPUDZ"
                        });
                });

            modelBuilder.Entity("WebAPI.Database.Dtos.UserNotificationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Invite")
                        .HasColumnType("bit");

                    b.Property<int>("ReceiveId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
