// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Database;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(WebApiDbContext))]
    partial class WebApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Database.Dtos.ProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectDtos");
                });

            modelBuilder.Entity("WebAPI.Database.Dtos.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "WOSPODJRSGCVXGFERZFL",
                            Email = "WOYQRKF",
                            Name = "GEZFE",
                            Skills = "VBLHTIGYCZAWVRGQKROF",
                            Status = "Open",
                            Title = "MMQSRINAFB"
                        },
                        new
                        {
                            Id = 2,
                            Description = "CJFZPQPYKETGRIAZWTAM",
                            Email = "VHMWQVE",
                            Name = "NDGXL",
                            Skills = "FKMZFEEEJVLMCVZQSLDA",
                            Status = "Open",
                            Title = "TASAOPOIIM"
                        },
                        new
                        {
                            Id = 3,
                            Description = "MRBKVBZZHYMVNQBYXGPN",
                            Email = "ZTZPLNY",
                            Name = "LCIMF",
                            Skills = "VYJXMCHHGCRTLDIHRQWJ",
                            Status = "Open",
                            Title = "KWRFVCDLKQ"
                        },
                        new
                        {
                            Id = 4,
                            Description = "CPIZZODRHZOONQIIELRH",
                            Email = "NPUYZZX",
                            Name = "HCSCB",
                            Skills = "LDTHVSHZJVEPLJRPZSKS",
                            Status = "Open",
                            Title = "AUOASTXOIF"
                        },
                        new
                        {
                            Id = 5,
                            Description = "KNAQDCEPANIERTZVBDGA",
                            Email = "JHNPPRX",
                            Name = "KLNZK",
                            Skills = "LCZKQRUDVDJCBUTRVIIL",
                            Status = "Open",
                            Title = "DUOXIVBLMY"
                        },
                        new
                        {
                            Id = 6,
                            Description = "XZKJEZPEGAMQJQLFMRVF",
                            Email = "OWIKUWK",
                            Name = "IYLTU",
                            Skills = "GKUWTVZEMTPCFEIUSSEU",
                            Status = "Open",
                            Title = "ZDYGJTMTSJ"
                        },
                        new
                        {
                            Id = 7,
                            Description = "BZLHFKZCNDDYAYLUPDAP",
                            Email = "TLJMCVE",
                            Name = "MWNNN",
                            Skills = "GUSFXPDPZEPEISCVVXQV",
                            Status = "Open",
                            Title = "EGAGTEIBNC"
                        },
                        new
                        {
                            Id = 8,
                            Description = "OZNHIUJBGQALNJQLIVKN",
                            Email = "IVJJOYF",
                            Name = "QVBLA",
                            Skills = "USXUIVFUVGUDIHIVMZKT",
                            Status = "Open",
                            Title = "YAPWDVKERD"
                        },
                        new
                        {
                            Id = 9,
                            Description = "GATIZFZHPZUDQZLZIUEG",
                            Email = "YNZAXRB",
                            Name = "PFYIZ",
                            Skills = "TJKAQGFLTLVXCYSWGGZI",
                            Status = "Open",
                            Title = "ELEUKRWIHP"
                        },
                        new
                        {
                            Id = 10,
                            Description = "LUKDEZPEQZQZIYVJNXGL",
                            Email = "XIBNSWG",
                            Name = "MUKFY",
                            Skills = "MHJUYIIFRBBZEIKAZLES",
                            Status = "Open",
                            Title = "MLXDNIKKKI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
